export const USER_REGISTER_INPUTS = [
  {
    id: 'firstName',
    label: 'First Name',
    variant: 'outlined',
    xs: 12,
    fullWidth: true,
  },
  {
    id: 'lastName',
    label: 'Last Name',
    variant: 'outlined',
    xs: 12,
    fullWidth: true,
  },
  {
    id: 'email',
    label: 'Email',
    variant: 'outlined',
    xs: 12,
    fullWidth: true,
    type: 'email',
  },
  {
    id: 'username',
    label: 'Username',
    variant: 'outlined',
    xs: 12,
    fullWidth: true,
  },
  {
    id: 'password',
    label: 'Password',
    variant: 'outlined',
    xs: 12,
    fullWidth: true,
    type: 'password',
  },
  {
    id: 'confirmPassword',
    label: 'Confirm Password',
    variant: 'outlined',
    xs: 12,
    fullWidth: true,
    type: 'password',
  },
];
