export const CONNECT_FORM_INPUTS = [
  {
    id: 1,
    title: 'Basic Info Inputs',
    inputs: [
      {
        id: 1,
        label: 'First Name',
        variant: 'filled',
        xs: 12,
        fullWidth: true,
        inputBackgroundColor: 'gainsboro',
        inputborderRadius: 4,
        inputPaddingBottom: 5,
        fontFamily: 'Kufam',
        labelColor: '#28282B',
      },
      {
        id: 2,
        label: 'Last Name',
        variant: 'filled',
        xs: 12,
        fullWidth: true,
        inputBackgroundColor: 'gainsboro',
        inputborderRadius: 4,
        inputPaddingBottom: 5,
        fontFamily: 'Kufam',
        labelColor: '#28282B',
      },
      {
        id: 3,
        label: 'Email',
        variant: 'filled',
        xs: 12,
        fullWidth: true,
        inputBackgroundColor: 'gainsboro',
        inputborderRadius: 4,
        inputPaddingBottom: 5,
        fontFamily: 'Kufam',
        labelColor: '#28282B',
      },
      {
        id: 4,
        label: 'Phone (Optional)',
        variant: 'filled',
        xs: 12,
        fullWidth: true,
        inputBackgroundColor: 'gainsboro',
        inputborderRadius: 4,
        inputPaddingBottom: 5,
        fontFamily: 'Kufam',
        labelColor: '#28282B',
      },
    ],
  },
  {
    id: 2,
    title: 'Message Text Area',
    inputs: [
      {
        id: 1,
        label: `Tell me somethin' good`,
        variant: 'filled',
        xs: 12,
        fullWidth: true,
        multiline: true,
        minRows: 11,
        maxRows: 11,
        inputBackgroundColor: 'gainsboro',
        inputborderRadius: 4,
        fontFamily: 'Kufam',
        labelColor: '#28282B',
      },
    ],
  },
];
