export const LEAD_INFO_INPUTS = [
  {
    id: 'firstName',
    label: 'First Name',
    variant: 'filled',
    color: 'primary',
    xs: 12,
    // md: 6,
    fullWidth: true,
    inputBackgroundColor: 'gainsboro',
    inputborderRadius: 4,
    inputPaddingBottom: 5,
    fontFamily: 'Kufam',
    labelColor: '#28282B',
  },
  {
    id: 'lastName',
    label: 'Last Name',
    color: 'primary',
    variant: 'filled',
    xs: 12,
    // md: 6,
    fullWidth: true,
    inputBackgroundColor: 'gainsboro',
    inputborderRadius: 4,
    inputPaddingBottom: 5,
    fontFamily: 'Kufam',
    labelColor: '#28282B',
  },
  {
    id: 'email',
    label: 'Email',
    color: 'primary',
    variant: 'filled',
    xs: 12,
    // md: 6,
    fullWidth: true,
    inputBackgroundColor: 'gainsboro',
    inputborderRadius: 4,
    inputPaddingBottom: 5,
    fontFamily: 'Kufam',
    labelColor: '#28282B',
  },
  {
    id: 'phone',
    label: 'Phone Number',
    color: 'primary',
    variant: 'filled',
    xs: 12,
    // md: 6,
    fullWidth: true,
    inputBackgroundColor: 'gainsboro',
    inputborderRadius: 4,
    inputPaddingBottom: 5,
    fontFamily: 'Kufam',
    labelColor: '#28282B',
  },
];
