export const BASIC_JOB_APP_INPUTS = [
  {
    id: 'name',
    label: 'Name',
    variant: 'standard',
    xs: 12,
    sm: 6,
    md: 3,
    fullWidth: true,
  },
  {
    id: 'email',
    label: 'Email',
    variant: 'standard',
    xs: 12,
    sm: 6,
    md: 3,
    fullWidth: true,
    type: 'email',
  },
  {
    id: 'phone',
    label: 'Phone',
    variant: 'standard',
    xs: 12,
    sm: 6,
    md: 3,
    fullWidth: true,
  },
  {
    id: 'job',
    label: 'What job are you applying for?',
    variant: 'standard',
    xs: 12,
    sm: 6,
    md: 3,
    fullWidth: true,
  },
  {
    id: 'summary',
    label: 'Write a short summary about yourself',
    variant: 'standard',
    xs: 12,
    fullWidth: true,
    multiline: true,
    minRows: 3,
  },
];
