export const BASIC_JOB_APP_INPUTS = [
  {
    id: 1,
    label: 'Name',
    variant: 'standard',
    xs: 12,
    sm: 6,
    md: 3,
    fullWidth: true,
  },
  {
    id: 2,
    label: 'Email',
    variant: 'standard',
    xs: 12,
    sm: 6,
    md: 3,
    fullWidth: true,
    type: 'email',
  },
  {
    id: 3,
    label: 'Phone',
    variant: 'standard',
    xs: 12,
    sm: 6,
    md: 3,
    fullWidth: true,
  },
  {
    id: 4,
    label: 'What job are you applying for?',
    variant: 'standard',
    xs: 12,
    sm: 6,
    md: 3,
    fullWidth: true,
  },
  {
    id: 5,
    label: 'Write a short summary about yourself',
    variant: 'standard',
    xs: 12,
    fullWidth: true,
    multiline: true,
    minRows: 3,
  },
];
